---
title: "about"
author: "Are Strom"
date: "April 9, 2019"
output: html_document
--- 

***  

### Introduction 

This application is intended as a planning tool for the intertidal shellfish management team at the WDFW Port Townsend office. The daily tide predictions in **Table 1** are generated using the `rtide` package, and are based on harmonics data from NOAA. 

Generating tide predictions in increments of one to fifteen minute intervals may take some time, so please limit predictions to periods of one month or less. For efficiency, the high-low only data in **Table 2** are derived from an internal dataset. The high-low data spans from 1970 to 2056, and can be queried for multiple beaches, and years, nearly instantaneously. 

### Disclaimer  

Tide predictions in this application are generated using the `rtide` R package. They are not suitable for navigation! 

Beach polygons in the map view are based on the 2018 beach layer used by aerial survey staff for data entry. The polygon boundaries indicated on the map are not legal boundaries! They have only been included for planning purposes and were originally designed to facilitate data entry. **Do not** assume these boundaries define areas open to public access. 

### Usage notes

Locations for tide predictions in **Table 1** can be selected using either the drop-down menu, or by clicking on the map. Only one beach or tide reference station can be selected at a time. Please limit the time-span of selections to one month. 

High and low tide predictions in **Table 2** can be selected for multiple tide reference stations and beaches simultaneously. You can select a full year (or more) of tides if needed. Tides can also be filtered by one or more strata. 

### Corrections for beaches

For now, only the time of tides at individual beaches have been corrected. Tide heights are still those of the reference stations. While the timing of tides varies considerably from north to south in Puget Sound, the tide height varies relatively little between reference and subordinate stations.

The primary difference in tide-time corrections used by this application versus corrections published by NOAA is for Zelatchet Point. NOAA data assumes the correction at Zelatchet Point should be -5 minutes relative to Seattle. However, nearly all other NOAA corrections in this stretch of the Canal, including at Bangor, Seabeck, and Pt Whitney varies by two minutes or less from Seattle. NOAAs Zelatchet Point data may be inappropriate for determining corrections at nearby beaches. 

This is corroborated by a Puget Sound tides model developed by the University of Washington (UW) and the NOAA Pacific Marine Environmental Laboratory (PMEL). This tides model was used to help interpolate corrections for beaches lying between official NOAA subordinate stations. Based on data from the tides model, the Zelatchet Point correction used by this application has been changed to +1. 

### Tide strata

The strata used as selection criteria in **Table 2** were developed to stratify recreational harvest estimates on the basis of tide height and whether the tide occurred on a weekend, holiday, or weekday. They are defined as:

* **HIGH:** Daytime weekday low tides (-0.1 to -1.9 ft), and daytime weekend, holiday, and weekday high tides (0.0 to 1.9 ft)
* **LOW:** Daytime weekday extreme low tides (-2.0 ft and below), and daytime weekend or holiday low tides (-0.1 to -1.9 ft)
* **ELOW:** Daytime weekend or holiday extreme low tides (-2.0 ft and below)
* **PLUS:** Daytime tides from 2.0 ft to 3.9 ft)
* **XPLUS:** Daytime tides 4.0 ft and above
* **NIGHT:** All night tides, from one hour before sunset to one hour after sunrise

### Next steps

A future version of this program will allow tide heights to be corrected for individual beaches. Currently, only the time of tides are corrected for beaches that lie between official NOAA reference stations. From a practical standpoint, those corrections will be minor, and do not affect calculations of tide strata. Because tide strata need to be standardized for any particular day, regardless of location, we use Seattle tides to define the strata. 

***









