---
title: "credits"
author: "Are Strom"
date: "April 9, 2019"
output: html_document
---  

#### Credits  

This application was built using the R programming language  

*R Core Team (2018). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria.*

The user interface is made possible by the `shiny` R package from RStudio

*Winston Chang, Joe Cheng, JJ Allaire, Yihui Xie and Jonathan McPherson (2018). shiny: Web Application Framework for R. R package version 1.2.0.*  

Tide predictions are generated using the `rtide` R package from Poisson Consulting

*Joe Thorley, Luke Miller and Abram Fleishman (2018). rtide: Tide Heights. R package version 0.0.5.* 

The user interface was inspired by the `rtide` shiny application developed by Seb Dalgarno of Poisson Consulting. 

Tide predictions rely on harmonics data from NOAA that were processed by David Flater for the `XTide` program. Both the `rtide` package and `XTide` have been published under the GPL-3 license.




